### ISSUE TITLE
peerDependency Issue

### ISSUE THREAD

**Issue by etanb** [jhabdas/material-ui-example#1]
There is some fundamental dependency issue between react and react-tap-event-plugin. I can't seem to get past the 'peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!' error message.

**Comment by jhabdas** [comment]
I completely forgot this repo existed! It was created using the [react-material-ui yeoman generator](https://github.com/shovon/generator-react-material-ui) during some exploratory development earlier this year. I was interested in playing around with MUI and I liked how the projected used the concept of generators to scaffold up new routes - similar to work I'd done using [scaffolt](https://github.com/paulmillr/scaffolt) in the past. Also the separation of Gulp into tasks was a nice pattern I wanted to adopt before Webpack broke onto the scene. Should've created that `npm-lockfile` when I had the chance! Though comically it probably still probably wouldn't have worked unless you were using a considerably old Node and/or NPM version.

Anyway, I tried a few of the dependencies and was able to get the app foundation functional again on `master`, resolving this issue. Nothing's displaying right now because React `0.14` had a considerable number of breaking changes and the new version of MUI relies on it. The changes are pretty systematic for the upgrade, so please feel free to send a PR my way (I have a feeling the Yeoman generator itself is going to die on the vine). Otherwise I'd suggest looking at a newer Yeoman generator or finding another seed or example project out there to start with as your base (nothing specific comes to mind, though I am building with MUI again on my [`lumpenradio-com`](https://github.com/jhabdas/lumpenradio-com) project if you'd like to see MUI together with Webpack (with no dependency on Gulp or Browserify).
